### ISSUE TITLE
Tax variable influence on the price

### ISSUE THREAD

**Issue by CorceiroPT** [JonnyMalman/EnergyRate#6]
I can’t see any difference in the price using different taxes values neither the information of the “Energy prices include tax of” on the Device Preview.
I could quite understand how that variable is used in the code.

**Comment by JonnyMalman** [comment]
Ouch... Let me overview this, maybe I did some changes to the tax calculation without testing 🤦‍♂️

**Comment by CorceiroPT** [comment]
Working now.
