### ISSUE TITLE
Negative eletrical costs

### ISSUE THREAD

**Issue by CorceiroPT** [JonnyMalman/EnergyRate#9]
Some country have economic mechanism associated with the energy crisis that allow prices of electricity to became negative in some periods.

It's not easy to implement them in Fibaro energy panel but I think it's not impossible... I just don't have the coding skills to do it (for now).

My idea is to consider that, when the rated price is negative, that we are producing energy and not consuming it and that we are producing it at the inverse negative cost. So if I get a -0,10 €/kWh and a given hour period, I need to convert all my kWh consumed in that period in the same value but "tagged" as produced at a given price of 0,10 €/kWh.

How can we do that on the Fibaro Energy panel? Where can I get some documentation that allow me to study how Fibaro manages the energy panel to know what variables should we "mess up"?

**Comment by JonnyMalman** [comment]
I fixed the negative rates with a local table in QA and don't use FIBARO Tariff table which can't handle it.

But I can't see that we actually produce any energy if the price is negative? The only way I can think of is if we have some kind of solar panels, wind turbines or something like that.
